pms/pms/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('',views.home,name='home'),
    path('new',views.new),
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('projects/',include('projects.urls')),
]

pms/projects/urls.py
from django.urls import path
from .views import CreateProject,ProjectList,ProjectShow,ChangeProjectStatus,ProjectEdit,ProjectTeam,DeleteProjectMember,CreateProjectModule,DeleteModuleFromCreateModule,DeleteModule,ProjectModuleShow,CreateTask,EditModule,DeleteTaskFromCreateTask,ShowTask,ChangeTaskStatus,EditTask,DeleteTask,AssignTask,UpdateStatusView,ProjectReport
from django.contrib.auth.views import LogoutView


urlpatterns = [
   path('create_project/',CreateProject.as_view(),name='create_project'),
   path('project_list/',ProjectList.as_view(),name='project_list'),
   path('project_show/<int:pk>',ProjectShow.as_view(),name='project_show'),
   path('change_project_status/<int:pk>/<int:project_id>/<str:status>',ChangeProjectStatus.as_view(),name='change_project_status'),
   path('project_edit/<int:pk>/',ProjectEdit.as_view(),name='project_edit'),
   path('project_team/<int:project_id>/',ProjectTeam.as_view(),name='project_team'),
   path('logout/',LogoutView.as_view(next_page='login'),name='logout'),
   path('delete_team_memeber/<int:pk>/<int:project_id>/',DeleteProjectMember.as_view(),name='delete_team_memeber'),
   path('create_project_module/<int:project_id>/',CreateProjectModule.as_view(),name='create_project_module'),
   path('delete_module_from_createModule/<int:pk>/<int:project_id>/',DeleteModuleFromCreateModule.as_view(),name='delete_module_from_createModule'),
   path('delete_module/<int:pk>/<int:project_id>/',DeleteModule.as_view(),name='delete_module'),
   path('projecct_module_show/<int:pk>/<project_id>/',ProjectModuleShow.as_view(),name='projecct_module_show'),
   path('create_task/<project_id>/<module_id>/',CreateTask.as_view(),name='create_task'),
   path('edit_module/<int:pk>/<int:project_id>',EditModule.as_view(),name='edit_module'),
   path('delete_task_from_create_task/<int:pk>/<project_id>/<module_id>/',DeleteTaskFromCreateTask.as_view(),name='delete_task_from_create_task'),
   path('show_task/<int:pk>',ShowTask.as_view(),name='show_task'),
   path('change_task_status/<int:pk>/<str:status>/',ChangeTaskStatus.as_view(),name='change_task_status'),
   path('edit_task/<int:pk>/',EditTask.as_view(),name='edit_task'),
   path('delete_task/<int:pk>/<int:module_id>/<int:project_id>',DeleteTask.as_view(),name='delete_task'),
   path('assign_task/<int:task_id>/<module_id>/<project_id>',AssignTask.as_view(),name='assign_task'),
   path('update_status/<int:pk>',UpdateStatusView.as_view(),name='update_status'),
   path('project_report/<int:pk>/',ProjectReport.as_view(),name='project_report'),
]

pms/projects/models.py
from django.db import models
from users.models import User
# Create your models here.

techChoices =(
    ("Python","Python"),
    ("Java","Java"),
    ("C++","C++"),
    ("C#","C#"),
)

projectStatus=(
    ('Active','Active'),
    ('Completed','Completed'),
    ('Cancelled','Cancelled'),
    ('On Hold','On Hold'),
)
class Project(models.Model):
    title=models.CharField( max_length=100)
    description=models.TextField()
    technology=models.CharField( max_length=100,choices=techChoices)
    estimated_hours=models.PositiveIntegerField()
    start_date=models.DateField()
    complateion_date=models.DateField()
    project_status=models.CharField( max_length=50, choices=projectStatus,default='Active')

    class Meta:
        db_table='Projects'

    def __str__(self):
        return self.title
    

class Project_team(models.Model):
    project = models.ForeignKey(Project,on_delete=models.CASCADE)        
    user = models.ForeignKey(User,on_delete=models.CASCADE,default=None)
    #in future you should use many to many field for user
    
    class Meta:
        db_table = "project_team"
        
    
    def __str__(self):
        return self.user.username  
    


class Project_module(models.Model):
    project=models.ForeignKey(Project, on_delete=models.CASCADE)
    module_name=models.CharField( max_length=50)
    description=models.TextField()
    estimated_hours=models.PositiveIntegerField()
    start_date=models.DateField( auto_now_add=False)

    class Meta:
        db_table="project_module"

    def __str__(self) -> str:
        return self.module_name

status_option=(
    ('Not Started','Not Started'),
    ('Progress','Progress'),
    ('complete','complete'),
)

class Task(models.Model):
    module=models.ForeignKey(Project_module, on_delete=models.CASCADE)
    project=models.ForeignKey(Project, on_delete=models.CASCADE)
    title=models.CharField( max_length=50)
    priority=models.CharField( max_length=50)
    description=models.TextField()
    status=models.CharField( max_length=50, choices=status_option)
    estimated_minutes=models.PositiveIntegerField()
    total_util_time=models.PositiveIntegerField()

    class Meta:
        db_table='task'

    def __str__(self) -> str:
        return self.title
    
class User_task(models.Model):
    userid=models.ForeignKey(User, on_delete=models.CASCADE)
    taksid=models.OneToOneField(Task, on_delete=models.CASCADE)

pms/projects/forms.py
from django import forms
from .models import Project,Project_team,Project_module,Task,User_task

class FormProject(forms.ModelForm):
    class Meta:
        model=Project
        fields="__all__"

class FormProjectEdit(forms.ModelForm):
    class Meta:
        model=Project
        fields="__all__"

class FormProjectTeam(forms.ModelForm):
    class Meta:
        model=Project_team
        fields='__all__'
        
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['project'].widget.attrs['disabled'] = True
    
class FormCreateModule(forms.ModelForm):
    class Meta:
        model=Project_module
        fields="__all__"
        
class FormEditModule(forms.ModelForm):
    class Meta:
        model=Project_module
        fields="__all__"

class FormTask(forms.ModelForm):
    class Meta:
        model=Task
        fields="__all__"

class FormEditTask(forms.ModelForm):
    class Meta:
        model=Task
        fields="__all__"

class FormAssignTask(forms.ModelForm):
    class Meta:
        model=User_task
        fields="__all__"

pms/projects/views.py
from django.shortcuts import render
from django.views.generic import CreateView,UpdateView,DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.shortcuts import redirect
from django.urls import reverse,reverse_lazy
from django.views import View
from .models import Project,Project_team,User,Project_module,Task,User_task
from .forms import FormProject,FormProjectEdit,FormProjectTeam,FormCreateModule,FormTask,FormEditModule,FormEditTask,FormAssignTask
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from django.utils.decorators import method_decorator
# Create your views here.

#Create Project
class CreateProject(CreateView):
    model=Project
    form_class=FormProject
    template_name='projects/create_project.html'
    success_url='/users/man_dash/'

#ProjectList
@method_decorator(never_cache, name='dispatch')
class ProjectList(ListView):
    model=Project
    context_object_name='project'
    template_name='projects/project_list.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["active"] = Project.objects.filter(project_status='Active').count() 
        context["completed"] = Project.objects.filter(project_status='Completed').count() 
        context["cancelled"] = Project.objects.filter(project_status='Cancelled').count() 
        context["Hold"] = Project.objects.filter(project_status='On Hold').count() 
        
        return context
    
#Project Show

class ProjectShow(DetailView):
    model=Project
    context_object_name='project'
    template_name='projects/project_show.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        project_id=self.kwargs['pk']
        context["developer"] =  Project_team.objects.filter(project=project_id)
        context["project_id"]=self.kwargs['pk']
        context["project_module"]=Project_module.objects.filter(project=project_id)
        return context
    


#Change Project Status
class ChangeProjectStatus(View):
    def post(self,request,pk,project_id,status):
        project_status=Project.objects.get(id=pk)
        print(status)
        if status == 'Active':
            project_status.project_status = "Active"
            project_status.save()
            return redirect(reverse('project_show',kwargs={'pk':self.kwargs['project_id']}))
        
        if status == 'Completed':
            project_status.project_status = "Completed"
            project_status.save()
            return redirect(reverse('project_show',kwargs={'pk':self.kwargs['project_id']}))
        
        if status == 'Cancelled':
            project_status.project_status = "Cancelled"
            project_status.save()
            return redirect(reverse('project_show',kwargs={'pk':self.kwargs['project_id']}))
        
        if status == 'On Hold':
            project_status.project_status = "On Hold"
            project_status.save()
            return redirect(reverse('project_show',kwargs={'pk':self.kwargs['project_id']}))
        
#Project Edit
class ProjectEdit(UpdateView):
    model=Project
    form_class=FormProjectEdit
    template_name='projects/edit_project.html'
    def get_success_url(self) -> str:
        success_url = reverse_lazy('project_show', kwargs={'pk': self.kwargs['pk']})
        return success_url
    
#Create Project Team
class ProjectTeam(CreateView):
    model=Project_team
    form_class=FormProjectTeam
    template_name='projects/project_team.html'

    def get_context_data(self, **kwargs) :
        context = super().get_context_data(**kwargs)
        project_id = self.kwargs.get('project_id') 
        context["developer"] = User.objects.filter(is_developer=True) 
        context["team_member"] = Project_team.objects.filter(project_id=project_id)
        context['delete_id']=project_id
        return context
    
    
    def get_initial(self):
        initial = super().get_initial()
        project_id = self.kwargs.get('project_id')  # Assuming project_id is passed in URL
        # project_id = 1
        if project_id:
            project = Project.objects.get(pk=project_id)
            initial['project'] = project  # Set the project field with the retrieved project
        return initial
    
    def get_success_url(self) -> str:
        success_url=reverse_lazy('project_team', kwargs={'project_id':self.kwargs['project_id']})
        return success_url
    

class CreateProjectModule(CreateView):
    model=Project_module
    form_class=FormCreateModule
    template_name='projects/project_module.html'
    def get_initial(self):
        initial = super().get_initial()
        project_id = self.kwargs.get('project_id')  # Assuming project_id is passed in URL
        if project_id:
            project = Project.objects.get(pk=project_id)
            initial['project'] = project  # Set the project field with the retrieved project
        return initial

    def get_success_url(self) -> str:
        project_id = self.kwargs.get('project_id')
        success_url = reverse_lazy('create_project_module', kwargs={'project_id': project_id})
        return success_url
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        project_id = self.kwargs.get('project_id')
        context["module"] = Project_module.objects.filter(project=project_id)
        context["project_id"]=project_id
        return context
    
class ProjectModuleShow(DetailView):
    model=Project_module
    context_object_name='module'
    template_name='projects/project_show_module.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["project_id"] = self.kwargs.get("project_id")
        context['task']=Task.objects.filter(module=self.kwargs['pk'])
        
        return context
    
    

class EditModule(UpdateView):
    model=Project_module
    form_class=FormEditModule
    template_name='projects/edit_module.html'
    def get_success_url(self) -> str:
        success_url=reverse_lazy('projecct_module_show',kwargs={'pk':self.kwargs['pk'],'project_id':self.kwargs['project_id']})
        return success_url

class CreateTask(CreateView):
    model=Task
    form_class=FormTask
    template_name='projects/create_task.html'
    def get_initial(self):
        initial = super().get_initial()
        project_id = self.kwargs.get('project_id')
        module_id = self.kwargs.get('module_id')
        if project_id:
            project = Project.objects.get(pk=project_id)
            initial['project'] = project  
        
        if module_id:
            module=Project_module.objects.get(pk=module_id)
            initial['module']=module
        return initial
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        module_id=self.kwargs['module_id']
        project_id = self.kwargs.get('project_id')
        context["task"] = Task.objects.filter(module=module_id) 
        context['project_id']=project_id
        context['module_id']=module_id
        return context
    
    def get_success_url(self) -> str:
        success_url=reverse_lazy('create_task',kwargs={'project_id':self.kwargs['project_id'],'module_id':self.kwargs['module_id']})
        return success_url
    
class ShowTask(DetailView):
    model=Task
    template_name='projects/show_task.html'
    context_object_name='task'

class ChangeTaskStatus(View):
     def post(self,request,pk,status):
        task_status=Task.objects.get(id=pk)
        print(status)
        if status == 'Not Started':
            task_status.status = "Not Started"
            task_status.save()
            return redirect(reverse('show_task',kwargs={'pk':self.kwargs['pk']}))
        
        if status == 'Progress':
            task_status.status = "Progress"
            task_status.save()
            return redirect(reverse('show_task',kwargs={'pk':self.kwargs['pk']}))
        
        if status == 'complete':
            task_status.status = "complete"
            task_status.save()
            return redirect(reverse('show_task',kwargs={'pk':self.kwargs['pk']}))
        
class EditTask(UpdateView):
    model=Task
    form_class=FormEditTask
    template_name='projects/edit_task.html'
    def get_success_url(self) -> str:
        success_url=reverse_lazy('show_task',kwargs={'pk':self.kwargs['pk']})
        return success_url

class AssignTask(CreateView):
    model=User_task
    form_class=FormAssignTask
    template_name='projects/assign_task.html'
    def get_initial(self):
        initial = super().get_initial()
        task_id=self.kwargs.get('task_id')
        print(task_id)
        if task_id:
            task = Task.objects.get(pk=task_id)
            initial['taksid'] = task  
        return initial
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        module_id=self.kwargs.get('module_id')
        context["task"] = Task.objects.filter(module=module_id)
        return context
    
    
    def get_success_url(self) -> str:
        success_url=reverse_lazy('projecct_module_show',kwargs={'pk':self.kwargs['module_id'],'project_id':self.kwargs['project_id']})
        return success_url

class UpdateStatusView(View):
    def post(self, request, pk):
        # Get the task instance
        task = Task.objects.get(id=pk)
        if task.status == "Not Started":
            task.status = "Progress"
        elif task.status == "Progress":
            task.status = "complete"
      
        task.save()
        
        return redirect(reverse('dev_dash'))
    
class ProjectReport(DetailView):
    model=Project
    context_object_name='project'
    template_name='projects/project_report.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

pms/templates/projects/create_project.html
{% extends "../base.html" %} {% load static %} {% block csslink %}
<link rel="stylesheet" href="{% static 'css/projects/create_project.css' %}" />
{% endblock csslink %} {% block content %}
<div class="regbox">
  <div id="manager">
    <div class="devreg_container">
      <h1 class="form-title">Create Project</h1>
      <form method="post">
        {% csrf_token %}
        <div class="main-user-info">
          <div class="user-input-box">
          <div class="title-tech">
            <div class="indiv">
              <label for="id_title">Title:</label>
              <input
                type="text"
                name="title"
                maxlength="100"
                required=""
                id="id_title"
                placeholder="Enter Project Title"
              />
            </div>
            <div class="indiv">
              <label for="id_technology">Technology:</label>

              <select name="technology" required="" id="id_technology">
                <option value="" selected="">---------</option>

                <option value="Python">Python</option>

                <option value="Java">Java</option>

                <option value="C++">C++</option>

                <option value="C#">C#</option>
              </select>
            </div>
          </div>
          <label for="id_description">Description:</label>

          <textarea
            name="description"
            cols="40"
            rows="5"
            required=""
            id="id_description"
            placeholder="Enter Description"
          ></textarea>

          <label for="id_estimated_hours">Estimated hours:</label>

          <input
            type="number"
            name="estimated_hours"
            min="0"
            required=""
            id="id_estimated_hours"
            placeholder="Enter Estimated Houres"
          />
          <div class="title-tech">
            <div class="indiv">
          <label for="id_start_date">Start date:</label>

          <input type="date" name="start_date" required="" id="id_start_date" />
        </div>
        <div class="indiv">
          <label for="id_complateion_date">Complateion date:</label>

          <input
            type="date"
            name="complateion_date"
            required=""
            id="id_complateion_date"
          />
        </div> 
        </div> 
       
        </div>
        <div>
          <label for="id_project_status"  style="color: white; font-size: 20px; font-weight: 600px;" ><b>Project Status:</b></label>

          <select name="project_status" id="id_project_status">
            <option value="Active" selected="">Active</option>

            <option value="Completed">Completed</option>

            <option value="Cancelled">Cancelled</option>

            <option value="On Hold">On Hold</option>
          </select>
        </div>
        <div class="form-submit-btn">
          <input type="submit" value="Submit"  />
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

pms/templates/projects/create_task.html
{% extends "../base.html" %} {% load static %} {% block csslink %}
<link rel="stylesheet" href="{% static 'css/projects/create_task.css' %}" />
{% endblock csslink %} {% block content %}
<div class="regbox">
    <div id="manager">
       
            <div class="devreg_container">
                <h1 class="form-title">Create Task</h1>
                <form method="post">
                    {% csrf_token %}

                    <div class="main-user-info">
                        <div class="user-input-box">
                            <div class="title-tech">
                                <div class="indiv" style="pointer-events: none;">
                                    <label for="id_title">Module</label>
                                    {{form.module}}
                                </div>
                                <div class="indiv" style="pointer-events: none;">
                                    <label for="id_technology">Project:</label>

                                    {{form.project}}
                                </div>
                            </div>
                            <div class="title-tech">
                                <div class="indiv">
                                    <label for="id_title">Title</label>
                                    {{form.title}}
                                </div>
                                <div class="indiv">
                                    <label for="id_technology">Priority:</label>

                                    {{form.priority}}
                                </div>
                            </div>
                            <label for="id_description">Description:</label>

                            {{form.description}}

                            <label for="id_estimated_hours"> Status:</label>

                            {{form.status}}
                            <div class="title-tech">
                                <div class="indiv">
                                    <label for="id_start_date">Estimated Minutes:</label>
                                    {{form.estimated_minutes}}
                                </div>
                                <div class="indiv">
                                    <label for="id_complateion_date">Total Util Time:</label>

                                    {{form.total_util_time}}
                                </div>
                            </div>

                        </div>
                        <div class="form-submit-btn" style="width: 100px;">
                            <input type="submit" value="Submit" />
                        </div>
                </form>
            </div>
            
        
    </div>
    <div style="width: 400px; margin-top: 20px;">
        <div class="card text-light text-center bg-white pb-2">
            <h1 style="color: black;">Tasks</h1>
          <div class="card-body text-dark">
            {% comment %} <h3 class="card-title">Project Module <a href="{% url "create_project_module" project_id %}" class="btn btn-primary">Create Module</a></h3> {% endcomment %}
            <table class="table">
              <thead class="table-dark">
                <th>Project</th>
                <th>Action</th>
              </thead>
              <tbody>
                {% for i in task %}
                <tr>
                  <td>{{i.title}}</td>
                  <td >
                    <a href="" class="btn btn-primary">Show</a> 
                    <a href="{% url 'delete_task_from_create_task' i.id project_id module_id %}" class="btn btn-danger">Delete</a> 
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>

            <!-- <button class="btn bg-warning text-dark">Learn More</button> -->
          </div>
        </div>
      </div>
</div>

{% endblock content %}

pms/templates/projects/edit_module.html
{% extends "../base.html" %} {% load static %} {% block csslink %}
<link rel="stylesheet" href="{% static 'css/projects/edit_module.css' %}" />
{% endblock csslink %} {% block content %}
<div class="regbox">
  <div id="manager">
    <div class="devreg_container">
      <h1 class="form-title">Edit Module</h1>
      <form method="post">
        {% csrf_token %}
        <div class="main-user-info">
          <div class="user-input-box">
          <div class="title-tech">
            <div class="indiv" style="pointer-events: none;">
                <label for="id_title" >Module:</label>
                {{ form.project }}
            </div>
            <div class="indiv">
              <label for="id_technology">Name:</label>
              {{form.module_name}}
            </div>
          </div>
          <label for="id_description">Description:</label>
          {{form.description}}
          <label for="id_estimated_hours">Estimated hours:</label>
        {{form.estimated_hours}}
          <div class="title-tech">
            <div class="indiv">
          <label for="id_start_date">Start date:</label>

          {{form.start_date}}
        </div>
        
        </div> 
       
        </div>
       
        <div class="form-submit-btn">
          <input type="submit" value="Update"  />
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

pms/templates/projects/edit_project.html
{% extends "../base.html" %} {% load static %} {% block csslink %}
<link rel="stylesheet" href="{% static 'css/projects/edit_project.css' %}" />
{% endblock csslink %} {% block content %}
<div class="regbox">
  <div id="manager">
    <div class="devreg_container">
      <h1 class="form-title">Create Project</h1>
      <form method="post">
        {% csrf_token %}
        <div class="main-user-info">
          <div class="user-input-box">
          <div class="title-tech">
            <div class="indiv">
                <label for="id_title">Title:</label>
                {{ form.title }}
            </div>
            <div class="indiv">
              <label for="id_technology">Technology:</label>
              {{form.technology}}
            </div>
          </div>
          <label for="id_description">Description:</label>
          {{form.description}}
          <label for="id_estimated_hours">Estimated hours:</label>
        {{form.estimated_hours}}
          <div class="title-tech">
            <div class="indiv">
          <label for="id_start_date">Start date:</label>

          {{form.start_date}}
        </div>
        <div class="indiv">
          <label for="id_complateion_date">Complateion date:</label>

        {{form.complateion_date}}
        </div> 
        </div> 
       
        </div>
        <div>
          <label for="id_project_status"  style="color: white; font-size: 20px; font-weight: 600px;" ><b>Project Status:</b></label>

          {{form.project_status}}
        </div>
        <div class="form-submit-btn">
          <input type="submit" value="Update"  />
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

pms/templates/projects/edit_task.html
{% extends "../base.html" %} {% load static %} {% block csslink %}
<link rel="stylesheet" href="{% static 'css/projects/edit_module.css' %}" />
{% endblock csslink %} {% block content %}
<div class="regbox">
  <div id="manager">
    <div class="devreg_container">
      <h1 class="form-title">Edit Task</h1>
      <form method="post">
        {% csrf_token %}
        <div class="main-user-info">
          <div class="user-input-box">
          <div class="title-tech">
            <div class="indiv" style="pointer-events: none;">
                <label for="id_technology">Project:</label>
                {{form.project}}
              </div>
            <div class="indiv" style="pointer-events: none;">
                <label for="id_title" >Module:</label>
                {{ form.module }}
            </div>
            
          </div>
          <div class="title-tech">
            <div class="indiv">
                <label for="id_technology">Title:</label>
                {{form.title}}
              </div>
            <div class="indiv">
                <label for="id_title" >priority:</label>
                {{ form.priority }}
            </div>
            
          </div>
          <label for="id_description">Description:</label>
          {{form.description}}
          <div class="indiv" style="pointer-events: none;">
            <label for="id_title" >Status:</label>
            {{ form.status }}
        </div>
          <div class="title-tech">
            <div class="indiv">
          <label for="id_start_date">Estimated minutes::</label>
          {{form.estimated_minutes}}
        </div>
        <div class="title-tech">
            <div class="indiv">
          <label for="id_start_date">Total util time:</label>
          {{form.total_util_time}}
            </div>
        </div> 
       
        </div>
       
        <div class="form-submit-btn">
          <input type="submit" value="Update"  />
        </div>
      </form>
    </div>
    </div>
  </div>
</div>
{% endblock content %}

pms/templates/projects/project_module.html
{% extends "../base.html" %} {% load static %} {% block csslink %}
<link rel="stylesheet" href="{% static 'css/projects/project_module.css' %}" />
{% endblock csslink %} {% block content %}
<div class="regbox">
  <div id="manager">
    <div style=" display: flex;">
            <div class="devreg_container">
              <h1 class="form-title">Create Module</h1>
              <form method="post">
                {% csrf_token %}
                <div class="main-user-info">
                  <div class="user-input-box">
                  <div class="title-tech">
                    <div class="indiv" style="pointer-events: none;">
                        <label for="id_technology" >Technology:</label>
                        {{form.project}}
                      </div>
                    <div class="indiv">
                        <label for="id_title">Title:</label>
                        {{ form.module_name }}
                    </div>
                    
                  </div>
                  <label for="id_description">Description:</label>
                  {{form.description}}
                

                  
                  <label for="id_estimated_hours">Estimated hours:</label>
                {{form.estimated_hours}}
                  <div class="title-tech">
                    <div class="indiv">
                        <label for="id_start_date">Start date:</label>
                        <input type="date" id="id_start_date" name="start_date" value="{{ form.start_date.value|date:'Y-m-d' }}">
                    </div>
                
                </div> 
              
                </div>
              
                <div class="form-submit-btn" >
                  <input type="submit" value="Submit"  />
                </div>
              </form>
              
                </div>
               
        </div>
        <div style=" width: 50%; display: flex;  flex-direction: column; align-items: center;">
          <h1 class="form-title">Module List <a href="{% url "project_show" project_id %}" class="btn btn-primary">Project</a></h1>
          <div style="width: 400px;">
            <div class="card text-light text-center bg-white pb-2">
              <div class="card-body text-dark">
          
                <table class="table">
                  
                  <thead class="table-dark">
                    <th>Developer</th>
                    <th>Action</th>
                  </thead>
                  <tbody>
                
                    {% for i in module %}
                    <tr>
                      <td>{{i.module_name}}</td>
                      <td>
                        <a href="{% url "project_show" i.id  %}" class="btn btn-primary">Show</a>
                        <a href="{% url "delete_module_from_createModule" i.id project_id  %}" class="btn btn-danger">Delete</a>
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
                <!-- <button class="btn bg-warning text-dark">learn More</button> -->
              </div>
              </div>
    </div>
    </div>

  </div>
</div>
{% endblock content %}